# Generated by Django 5.1.5 on 2025-01-26 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripción')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha Publicación')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='libros/', verbose_name='Portada')),
                ('ejemplares', models.IntegerField(verbose_name='Ejemplares')),
                ('recomendaciones', models.PositiveIntegerField(default=0, verbose_name='Recomendaciones')),
                ('condicion', models.CharField(choices=[('Disponible', 'Disponible'), ('Sin Ejemplares', 'Sin Ejemplares')], default='Disponible', max_length=20, verbose_name='Condición')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libro.autor', verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libro.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recomendacion', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libro.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Recomendacion',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
    ]
