# Generated by Django 5.1.5 on 2025-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
    ]
