# Generated by Django 5.1.5 on 2025-01-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_alter_prestamo_recargo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='recargo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Recargo Total'),
        ),
    ]
